updated the OS in single.py and readme
LambdaTest/pyunit-selenium-sample pull request #10
Opened 2022-07-11 10:07 UTC by Saurabh-LT

2022-07-11 10:46 UTC, mukesh-lt approved these changes

2022-07-11 11:39 UTC, sururocks commented on README.md
>  ln 18:           "version": '81.0',
move to latest or latest-1 so it not break in future

2022-07-11 11:40 UTC, sururocks requested changes
change requested

2022-07-12 07:43 UTC, sururocks approved these changes

2022-07-12 07:43 UTC, merged